import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Deaths from "../components/charts/Deaths";
import Search from "../components/Search";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>COVID Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Search />
      <Deaths />
    </div>
  );
};

export default Home;
