import { useState } from "react";
import { NextPage, GetStaticProps, InferGetStaticPropsType } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Content from "../components/Content";
import { Countries } from "../interfaces";

const Home: NextPage = ({
  countries,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  const [country, setCountry] = useState("");
  const countrySelected: boolean = false;

  console.log(countries);

  return (
    <div className={styles.container}>
      <Head>
        <title>COVID Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {countrySelected ? <Content /> : ""}
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch("https://api.covid19api.com/countries");
  const countries: Countries[] = await res.json(); // countries[]
  return {
    props: {
      countries,
    },
  };
};
